all:
	gcc -std=c99 -pedantic -Wall -pthread -lm dotproduct.c -o dotproduct
	gcc -std=c99 -pedantic -Wall -pthread -lm sumscalar.c -o sumscalar
	gcc -std=c99 -pedantic -Wall -pthread -lm sumscalar.padding.c -o sumscalar.padding
